### ISSUE TITLE
Marshalling fails in second run.

### ISSUE THREAD

**Issue by juanmav** [highsource/jsonix#57] opened 2015-02-03 14:47 UTC
I am not sure if it is a Jsonix bug or not. In the first run de marshalling run right but in the second one (after refresh on pressing F5) the marshalling fails without returning any error.

the code:

Creating Jsonix Context.
```javascript
Ows4js.Csw.jsonnixContext = new Jsonix.Context(
    [
        OWS_1_0_0,
        DC_1_1,
        DCT,
        XLink_1_0,
        SMIL_2_0,
        SMIL_2_0_Language,
        GML_3_1_1,
        Filter_1_1_0,
        CSW_2_0_2
    ]
);

Ows4js.Csw.marshalDocument = function(object){
    return Ows4js.Csw.jsonnixContext.createMarshaller().marshalDocument(object);
}; 
```

Call Marshaling

```javascript
   .......
   // Create de GetRecords Action.
    var recordAction = new Ows4js.Csw.GetRecords(startPosition, maxRecords, query);
    // XML to Post.
    var myXML = Ows4js.Csw.marshalDocument(recordAction);
   ......
```

First run:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<csw:GetRecords xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" service="CSW" version="2.0.2" resultType="results" startPosition="1" maxRecords="10">
	<csw:Query typeNames="csw:Record">
		<csw:ElementSetName>full</csw:ElementSetName>
		<csw:Constraint version="1.1.0">
			<ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">
				...............
			</ogc:Filter>
		</csw:Constraint>
	</csw:Query>
</csw:GetRecords>
```

Second run:

```javascript
#documentURL: ""
activeElement: 
nullanchors: HTMLCollection[0]
applets: HTMLCollection[0]
baseURI: null
.............
```

The full code can by found at https://github.com/juanmav/ows.js (examples/index.html).

Any idea what is wrong ?

Thanks in advance
JM

**Comment by highsource** [comment] 2015-02-03 15:07
Hm, strange. I'll take a look. I first thought you reuse the marshaller -
but now, you create them anew, as it should be. I'll take a look.

Could you create a JSON for me to test? I'll add a double-marshalling test
case here:

https://github.com/highsource/ogc-schemas/blob/master/scripts/tests/CSW/2.0.2/CSW_2_0_2.js

**Comment by juanmav** [comment] 2015-02-03 18:33
of course

```javascript
obj = {
    "name": {
        "key": "{http://www.opengis.net/cat/csw/2.0.2}GetRecords",
        "localPart": "GetRecords",
        "namespaceURI": "http://www.opengis.net/cat/csw/2.0.2",
        "prefix": "csw",
        "string": "{http://www.opengis.net/cat/csw/2.0.2}csw:GetRecords"
    },
    "value": {
        "TYPE_NAME": "CSW_2_0_2.GetRecordsType",
        "startPosition": 1,
        "maxRecords": 10,
        "resultType": "results",
        "service": "CSW",
        "version": "2.0.2",
        "abstractQuery": {
            "name": {
                "key": "{http://www.opengis.net/cat/csw/2.0.2}Query",
                "localPart": "Query",
                "namespaceURI": "http://www.opengis.net/cat/csw/2.0.2",
                "prefix": "csw",
                "string": "{http://www.opengis.net/cat/csw/2.0.2}csw:Query"
            },
            "value": {
                "TYPE_NAME": "CSW_2_0_2.QueryType",
                "elementSetName": {
                    "TYPE_NAME": "CSW_2_0_2.ElementSetNameType",
                    "value": "full"
                },
                "typeNames": [
                    {
                        "key": "{http://www.opengis.net/cat/csw/2.0.2}Record",
                        "localPart": "Record",
                        "namespaceURI": "http://www.opengis.net/cat/csw/2.0.2",
                        "prefix": "csw",
                        "string": "{http://www.opengis.net/cat/csw/2.0.2}csw:Record"
                    }
                ],
                "constraint": {
                    "TYPE_NAME": "CSW_2_0_2.QueryConstraintType",
                    "version": "1.1.0",
                    "filter": {
                        "name": {
                            "key": "{http://www.opengis.net/ogc}Filter",
                            "localPart": "Filter",
                            "namespaceURI": "http://www.opengis.net/ogc",
                            "prefix": "ogc",
                            "string": "{http://www.opengis.net/ogc}ogc:Filter"
                        },
                        "value": {
                            "TYPE_NAME": "Filter_1_1_0.FilterType",
                            "logicOps": {
                                "name": {
                                    "key": "{http://www.opengis.net/ogc}And",
                                    "localPart": "And",
                                    "namespaceURI": "http://www.opengis.net/ogc",
                                    "prefix": "ogc",
                                    "string": "{http://www.opengis.net/ogc}ogc:And"
                                },
                                "value": {
                                    "TYPE_NAME": "Filter_1_1_0.BinaryLogicOpType",
                                    "comparisonOpsOrSpatialOpsOrLogicOps": [
                                        {
                                            "name": {
                                                "key": "{http://www.opengis.net/ogc}PropertyIsLike",
                                                "localPart": "PropertyIsLike",
                                                "namespaceURI": "http://www.opengis.net/ogc",
                                                "prefix": "ogc",
                                                "string": "{http://www.opengis.net/ogc}ogc:PropertyIsLike"
                                            },
                                            "value": {
                                                "TYPE_NAME": "Filter_1_1_0.PropertyIsLikeType",
                                                "literal": {
                                                    "TYPE_NAME": "Filter_1_1_0.LiteralType",
                                                    "content": [
                                                        "%water%"
                                                    ]
                                                },
                                                "propertyName": {
                                                    "TYPE_NAME": "Filter_1_1_0.PropertyNameType",
                                                    "content": "dc:title"
                                                },
                                                "escapeChar": "",
                                                "singleChar": "_",
                                                "wildCard": "%"
                                            }
                                        },
                                        {
                                            "name": {
                                                "key": "{http://www.opengis.net/ogc}PropertyIsLike",
                                                "localPart": "PropertyIsLike",
                                                "namespaceURI": "http://www.opengis.net/ogc",
                                                "prefix": "ogc",
                                                "string": "{http://www.opengis.net/ogc}ogc:PropertyIsLike"
                                            },
                                            "value": {
                                                "TYPE_NAME": "Filter_1_1_0.PropertyIsLikeType",
                                                "literal": {
                                                    "TYPE_NAME": "Filter_1_1_0.LiteralType",
                                                    "content": [
                                                        "%polution%"
                                                    ]
                                                },
                                                "propertyName": {
                                                    "TYPE_NAME": "Filter_1_1_0.PropertyNameType",
                                                    "content": "dc:subject"
                                                },
                                                "escapeChar": "",
                                                "singleChar": "_",
                                                "wildCard": "%"
                                            }
                                        },
                                        {
                                            "name": {
                                                "key": "{http://www.opengis.net/ogc}BBOX",
                                                "localPart": "BBOX",
                                                "namespaceURI": "http://www.opengis.net/ogc",
                                                "prefix": "ogc",
                                                "string": "{http://www.opengis.net/ogc}ogc:BBOX"
                                            },
                                            "value": {
                                                "TYPE_NAME": "Filter_1_1_0.BBOXType",
                                                "envelope": {
                                                    "name": {
                                                        "key": "{http://www.opengis.net/gml}Envelope",
                                                        "localPart": "Envelope",
                                                        "namespaceURI": "http://www.opengis.net/gml",
                                                        "prefix": "gml",
                                                        "string": "{http://www.opengis.net/gml}gml:Envelope"
                                                    },
                                                    "value": {
                                                        "TYPE_NAME": "GML_3_1_1.EnvelopeType",
                                                        "srsName": "urn:x-ogc:def:crs:EPSG:6.11:4326",
                                                        "lowerCorner": {
                                                            "TYPE_NAME": "GML_3_1_1.DirectPositionType",
                                                            "value": [
                                                                -80,
                                                                150
                                                            ]
                                                        },
                                                        "upperCorner": {
                                                            "TYPE_NAME": "GML_3_1_1.DirectPositionType",
                                                            "value": [
                                                                80,
                                                                -150
                                                            ]
                                                        }
                                                    }
                                                },
                                                "propertyName": {
                                                    "TYPE_NAME": "Filter_1_1_0.PropertyNameType",
                                                    "content": "ows:BoundingBox"
                                                }
                                            }
                                        }
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by highsource** [comment] 2015-02-03 22:15
Somehow I fail to reproduce it.

When I just try to start [`examples/index.html`](https://github.com/juanmav/ows.js/blob/master/examples/index.html) I get the following errors:

![image](https://cloud.githubusercontent.com/assets/6707996/6030632/1646dc04-abf9-11e4-8d56-91ef7b8ceb75.png)

I guess it expects a local proxy server which I don't have.

I have also tried it in the [JSFiddle](http://jsfiddle.net/lexi/6skd7x8u/15/) but it also worked fine.

So unfortunately I can't really reproduce it.

I thing the "best" way would be to extends Node.js `package.json` to add there a simple server which would serve files from the `example` directory AND also include a simple proxy. Then it would be possible to `npm start` this server and the test via `localhost`. I never did this though

BTW. You don't need these [`key`](https://github.com/juanmav/ows.js/blob/master/src/csw.js#L220) and [`string`](https://github.com/juanmav/ows.js/blob/master/src/csw.js#L224).

**Comment by juanmav** [comment] 2015-02-04 03:33
At the moment I am using chrome with `--disable-web-security` (in ubuntu). I will add the proxy to the `grunt-serve` task to avoid `Access-Control-Allow-Origin`

**Comment by highsource** [comment] 2015-02-04 08:10
@juanmav I actually started `chrome` with `--disable-web-security`. Maybe I'm missing something. Should I just open the local file or start something and go via some localhost address?

**Comment by juanmav** [comment] 2015-02-04 14:00
@highsource I am using `http-server` (to install it`npm install http-server -g`). Run it in the root folder and go to `http://127.0.0.1:8080/examples/index.html`

I am going to add a `grunt-serve` task and a proxy with it to simplify the process to test the ows.js also improve the readme file

**Comment by highsource** [comment] 2015-02-04 14:11
Ok, I'll give it a try.

**Comment by highsource** [comment] 2015-02-04 21:28
Ok, this looks like this issue:

http://stackoverflow.com/questions/27221971/why-does-console-logdocument-getelementbyid-blah-give-different-log-mess

So the marshalling actually does not fail, it's Chrome which logs DOM differently (seems to be random).

**Comment by highsource** [comment] 2015-02-04 21:29
Closed as won't fix as this does not seem to be Jsonix issue.

**Closed by highsource** 2015-02-04 21:28 UTC
