### ISSUE TITLE
Support of gYearMonth, gYear, gMonthDay, gMonth, gDay types.

### ISSUE THREAD

**Issue by duschata** [highsource/jsonix#73] opened 2015-03-30 14:10 UTC
Hello All,
I've tried to compile a XSD Schema including xsd:gYear(...) to a mapping file. Marshalling and unmarshalling fails. Take a look at the attached index.html. I've tried to fix it (also available in the .zip), its not implemented yet (Snapshot 2.1.5). Have you planned to implement the support for gYear...?.
Kind Regards
Thomas Grabietz 
file: https://mega.co.nz/#!ylkhXKgS!WhHt0OQSCSA91DvxB9BHVl2wx4g8G7DoKhZNcHK8N_Q

**Comment by highsource** [comment] 2015-03-30 14:27
I can't access your attachment, sorry. Please send me the mail to valikov(-)gmx.net.

Actually `gYear`, `gMonth` and so on should be supported already, see [here](https://github.com/highsource/jsonix/tree/master/scripts/src/main/javascript/org/hisrc/jsonix/Jsonix/Schema/XSD).

**Comment by highsource** [comment] 2015-03-30 14:29
Or even better please make a JSFiddle (see [this example](http://jsfiddle.net/ivanj/76rvzjw5/5/)).

**Comment by highsource** [comment] 2015-03-30 19:50
See also:
http://jira.highsource.org/browse/JSNX-3

**Comment by highsource** [comment] 2015-03-30 20:24
See also:
https://code.google.com/p/jsdatatypelibrary/source/browse/trunk/jsdatatypelibrary/datatype_library.js

**Comment by highsource** [comment] 2015-03-30 20:26
Reproduced.

The status is: `g*` types are really not supported yet.

* `Jsonix.Schema.XSD.Calendar` should be extended to support `gYearMonth`, `gYear`, `gMonthDay`, `gMonth`, `gDay` types.
* `Jsonix.Schema.XSD.G*` types extend `Jsonix.Schema.XSD.Calendar` and call the appropriate parse/print methods.

**Comment by highsource** [comment] 2015-03-31 04:40
Implementation hints:

* [Calendar](https://github.com/highsource/jsonix/blob/master/scripts/src/main/javascript/org/hisrc/jsonix/Jsonix/Schema/XSD/Calendar.js) should detect the pattern [here](https://github.com/highsource/jsonix/blob/master/scripts/src/main/javascript/org/hisrc/jsonix/Jsonix/Schema/XSD/Calendar.js#L16-L24). The best would be probably with a regexp. [These](https://code.google.com/p/jsdatatypelibrary/source/browse/trunk/jsdatatypelibrary/datatype_library.js) are good hints, but I won't use the code directly because I'm not sure those expressions are correct and also because of the license. Better to write regular expressions from scratch based on the [spec](http://www.w3.org/TR/xmlschema-2/#gYearMonth) 3.2.10 - 3.2.14.
* Add `parseGYearMonth` ... `parseGDay` methods called when a certain regexp is detected in `parse`
* The reverse in `print`: check what the object contains, call the `printGYearMonth`...`printGDay` accordingly, throw an error if the combination does not match any type.
* In [GYearMonth](https://github.com/highsource/jsonix/blob/master/scripts/src/main/javascript/org/hisrc/jsonix/Jsonix/Schema/XSD/GYearMonth.js) ... [GDay](https://github.com/highsource/jsonix/blob/master/scripts/src/main/javascript/org/hisrc/jsonix/Jsonix/Schema/XSD/GDay.js), extend the Calendar and call the appropriate print/parse methods. Validate the input both on print and parse.
* Tests go [here](https://github.com/highsource/jsonix/blob/master/nodejs/scripts/tests/xsd.js#L140-L198), will probably make sense splitting in smaller test methods. To build, you'll need to `mvn clean install` `scripts` and then `mvn clean install` in `nodejs/scripts` and then you should be able to `npm test`. This is awkward at the moment.
* Issue-speicific test is [here](https://github.com/highsource/jsonix/tree/master/nodejs/scripts/tests/GH73), at the moment [commented out](https://github.com/highsource/jsonix/blob/master/nodejs/scripts/tests/issues.js#L8)
* Relevant XJC plugin class is [here](https://github.com/highsource/jsonix-schema-compiler/blob/master/compiler/src/main/java/org/hisrc/jsonix/compilation/CreateTypeInfoDeclarationVisitor.java#L120-L124), basically you'll have to comment out the mappings.
* This is more or less it. Probably a few tests will fail or will have to be extended, but that's minor.

**Comment by highsource** [comment] 2015-06-28 11:12
I think this works well enough, so I'll close this issue. Please test and file new issues if you miss something.

**Closed by highsource** 2015-06-28 11:12 UTC
Labels: enhancement
