### ISSUE TITLE
Unmarshal Empty Element

### ISSUE THREAD

**Issue by IvanJosipovic** [highsource/jsonix#71] opened 2015-03-29 19:57 UTC
Hi Alexey,

I have an need to output empty elements.
For example, if i unmarshal an empty element < installDir />
Then, when i marshal the object jsonix returns, no element.

Fiddle: http://jsfiddle.net/ivanj/76rvzjw5/5/

Is there a simple way to achieve this?

Thank you for this awesome project,
Ivan

**Comment by highsource** [comment] 2015-03-29 20:06
Looks like a bug to me. This should actually an empty string, but it is not unmarshalled at all.

**Comment by highsource** [comment] 2015-03-29 20:08
@IvanJosipovic Thank you for the feedback, the report and the fiddle. Is it OK for me to use mappings from your feedle in a test case?

**Comment by IvanJosipovic** [comment] 2015-03-29 20:09
Of course, please use the mappings. Thank you for the quick response!

**Comment by highsource** [comment] 2015-03-29 20:15
Reproduced, is a bug, scheduled for 2.1.5.

**Comment by highsource** [comment] 2015-03-29 21:48
@IvanJosipovic This should be fixed now, please try the latest scripts.

Rescheduling as 2.2.0 since it has a potential to be backwards-incompatible.

**Comment by highsource** [comment] 2015-03-29 21:51
@IvanJosipovic Your fidlle also works as expected now. You may need to reload/clear the cache though.

**Comment by IvanJosipovic** [comment] 2015-03-29 21:51
Confirmed, thank you!

**Closed by highsource** 2015-03-29 21:51 UTC
Labels: bug
